version: '3.8'
services:
  mysql: # https://hub.docker.com/_/mysql
    image: 'mysql:8.0.27'
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'pw123456'
      MYSQL_DATABASE: 'devdb'
      MYSQL_USER: 'user1'
      MYSQL_PASSWORD: 'pw123456'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
  axonserver: # axonserver: # https://hub.docker.com/r/axoniq/axonserver
    image: 'axoniq/axonserver:4.5.8'
    restart: always
    environment:
      axoniq.axonserver.name : 'demo axon server'
      axoniq.axonserver.hostname : 'localhost'
      axoniq.axonserver.devmode.enabled : 'true'
    ports:
      - '8024:8024'
      - '8124:8124'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
