/*
 * This file is generated by jOOQ.
 */
package com.example.demo.cart.domain.projecttions;


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/** 購物車資料 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(
    name = "cart",
    uniqueConstraints = {
      @UniqueConstraint(
          name = "KEY_cart_PRIMARY",
          columnNames = {"cart_number"})
    })
public class CartEntity implements Serializable {

  private static final long serialVersionUID = 1L;

  private String cartNumber;
  private String customerName;
  private Integer price;

  public CartEntity() {}

  public CartEntity(CartEntity value) {
    this.cartNumber = value.cartNumber;
    this.customerName = value.customerName;
    this.price = value.price;
  }

  public CartEntity(String cartNumber, String customerName, Integer price) {
    this.cartNumber = cartNumber;
    this.customerName = customerName;
    this.price = price;
  }

  /** Getter for <code>devdb.cart.cart_number</code>. */
  @Id
  @Column(name = "cart_number", nullable = false, length = 60)
  @NotNull
  @Size(max = 60)
  public String getCartNumber() {
    return this.cartNumber;
  }

  /** Setter for <code>devdb.cart.cart_number</code>. */
  public void setCartNumber(String cartNumber) {
    this.cartNumber = cartNumber;
  }

  /** Getter for <code>devdb.cart.customer_name</code>. 客戶名稱 */
  @Column(name = "customer_name", nullable = false, length = 60)
  @NotNull
  @Size(max = 60)
  public String getCustomerName() {
    return this.customerName;
  }

  /** Setter for <code>devdb.cart.customer_name</code>. 客戶名稱 */
  public void setCustomerName(String customerName) {
    this.customerName = customerName;
  }

  /** Getter for <code>devdb.cart.price</code>. 金額 */
  @Column(name = "price", nullable = false, precision = 10)
  @NotNull
  public Integer getPrice() {
    return this.price;
  }

  /** Setter for <code>devdb.cart.price</code>. 金額 */
  public void setPrice(Integer price) {
    this.price = price;
  }
}
