/*
 * This file is generated by jOOQ.
 */
package com.example.demo.cart.domain.projecttions;


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/** 購物車商品資料 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(
    name = "cart_product",
    uniqueConstraints = {
      @UniqueConstraint(
          name = "KEY_cart_product_PRIMARY",
          columnNames = {"id"})
    },
    indexes = {@Index(name = "cart_number", columnList = "cart_number ASC")})
public class CartProductEntity implements Serializable {

  private static final long serialVersionUID = 1L;

  private Integer id;
  private String cartNumber;
  private String productId;
  private String productTittle;
  private Integer price;

  public CartProductEntity() {}

  public CartProductEntity(CartProductEntity value) {
    this.id = value.id;
    this.cartNumber = value.cartNumber;
    this.productId = value.productId;
    this.productTittle = value.productTittle;
    this.price = value.price;
  }

  public CartProductEntity(
      Integer id, String cartNumber, String productId, String productTittle, Integer price) {
    this.id = id;
    this.cartNumber = cartNumber;
    this.productId = productId;
    this.productTittle = productTittle;
    this.price = price;
  }

  /** Getter for <code>devdb.cart_product.id</code>. */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id", nullable = false, precision = 10)
  public Integer getId() {
    return this.id;
  }

  /** Setter for <code>devdb.cart_product.id</code>. */
  public void setId(Integer id) {
    this.id = id;
  }

  /** Getter for <code>devdb.cart_product.cart_number</code>. 購物車編號 */
  @Column(name = "cart_number", nullable = false, length = 60)
  @NotNull
  @Size(max = 60)
  public String getCartNumber() {
    return this.cartNumber;
  }

  /** Setter for <code>devdb.cart_product.cart_number</code>. 購物車編號 */
  public void setCartNumber(String cartNumber) {
    this.cartNumber = cartNumber;
  }

  /** Getter for <code>devdb.cart_product.product_id</code>. 商品編號 */
  @Column(name = "product_id", nullable = false, length = 10)
  @NotNull
  @Size(max = 10)
  public String getProductId() {
    return this.productId;
  }

  /** Setter for <code>devdb.cart_product.product_id</code>. 商品編號 */
  public void setProductId(String productId) {
    this.productId = productId;
  }

  /** Getter for <code>devdb.cart_product.product_tittle</code>. 商品標題 */
  @Column(name = "product_tittle", nullable = false, length = 10)
  @NotNull
  @Size(max = 10)
  public String getProductTittle() {
    return this.productTittle;
  }

  /** Setter for <code>devdb.cart_product.product_tittle</code>. 商品標題 */
  public void setProductTittle(String productTittle) {
    this.productTittle = productTittle;
  }

  /** Getter for <code>devdb.cart_product.price</code>. 金額 */
  @Column(name = "price", nullable = false, precision = 10)
  @NotNull
  public Integer getPrice() {
    return this.price;
  }

  /** Setter for <code>devdb.cart_product.price</code>. 金額 */
  public void setPrice(Integer price) {
    this.price = price;
  }
}
